### ISSUE TITLE
Remove manual <title> tag insertion in document head

### ISSUE THREAD

**Issue by cjg89** [UCF/BOT-Bootstrap#8]
This theme utilizes title-tag theme support, so we should remove the code in this theme that manually prints a `<title>` tag in the document head.

See:
https://github.com/UCF/BOT-Bootstrap/blob/master/functions/base.php#L1029
https://github.com/UCF/BOT-Bootstrap/blob/master/functions/base.php#L1153

**Comment by rjucf** [comment]
Closing, this was fixed:
https://github.com/UCF/BOT-Bootstrap/pull/20
